version: '3'
services:
    app:
        container_name: video-hosting-vue-app
        build:
            context: .
            dockerfile: Dockerfile

        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
        - 1234:8080